linters:
  disable-all: true
  enable:
    - staticcheck
    - revive
    - decorder
linters-settings:
  staticcheck:
    go: "1.20"
    checks: [ "all" ]
  revive:
    max-open-files: 2048
    ignore-generated-header: true
    severity: error
    enable-all-rules: true
    confidence: 0.1
    rules:
      - name: add-constant
        severity: warning
        disabled: false
        arguments:
          - maxLitCount: "3"
            allowStrs: '""'
            allowInts: "0,1,2"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
      - name: argument-limit
        severity: warning
        disabled: false
        arguments: [ 4 ]
      - name: atomic
        severity: warning
        disabled: false
      - name: banned-characters
        severity: warning
        disabled: false
        arguments: [ "Ω", "Σ", "σ", "7" ]
      - name: bare-return
        severity: warning
        disabled: false
      - name: blank-imports
        severity: warning
        disabled: false
      - name: bool-literal-in-expr
        severity: warning
        disabled: false
      - name: call-to-gc
        severity: warning
        disabled: false
      - name: cognitive-complexity
        severity: warning
        disabled: false
        arguments: [ 7 ]
      - name: comment-spacings
        severity: warning
        disabled: false
        arguments:
          - mypragma
          - otherpragma
      - name: confusing-naming
        severity: warning
        disabled: false
      - name: confusing-results
        severity: warning
        disabled: false
      - name: constant-logical-expr
        severity: warning
        disabled: false
      - name: context-as-argument
        severity: warning
        disabled: false
        arguments:
          - allowTypesBefore: "*testing.T,*github.com/user/repo/testing.Harness"
      - name: context-keys-type
        severity: warning
        disabled: false
      - name: cyclomatic
        severity: warning
        disabled: false
        arguments: [ 3 ]
      - name: datarace
        severity: warning
        disabled: false
      - name: deep-exit
        severity: warning
        disabled: false
      - name: defer
        severity: warning
        disabled: false
        arguments:
          - [ "call-chain", "loop" ]
      - name: dot-imports
        severity: warning
        disabled: false
      - name: duplicated-imports
        severity: warning
        disabled: false
      - name: early-return
        severity: warning
        disabled: false
      - name: empty-block
        severity: warning
        disabled: false
      - name: empty-lines
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: error-strings
        severity: warning
        disabled: false
      - name: errorf
        severity: warning
        disabled: false
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: file-header
        severity: warning
        disabled: false
        arguments:
          - This is the text that must appear at the top of source files.
      - name: flag-parameter
        severity: warning
        disabled: false
      - name: function-result-limit
        severity: warning
        disabled: false
        arguments: [ 2 ]
      - name: function-length
        severity: warning
        disabled: false
        arguments: [ 10, 0 ]
      - name: get-return
        severity: warning
        disabled: false
      - name: identical-branches
        severity: warning
        disabled: false
      - name: if-return
        severity: warning
        disabled: false
      - name: increment-decrement
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
      - name: imports-blacklist
        severity: warning
        disabled: false
        arguments:
          - "crypto/md5"
          - "crypto/sha1"
      - name: import-shadowing
        severity: warning
        disabled: false
      - name: line-length-limit
        severity: warning
        disabled: false
        arguments: [ 80 ]
      - name: max-public-structs
        severity: warning
        disabled: false
        arguments: [ 3 ]
      - name: modifies-parameter
        severity: warning
        disabled: false
      - name: modifies-value-receiver
        severity: warning
        disabled: false
      - name: nested-structs
        severity: warning
        disabled: false
      - name: optimize-operands-order
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: range
        severity: warning
        disabled: false
      - name: range-val-in-closure
        severity: warning
        disabled: false
      - name: range-val-address
        severity: warning
        disabled: false
      - name: receiver-naming
        severity: warning
        disabled: false
      - name: redefines-builtin-id
        severity: warning
        disabled: false
      - name: string-of-int
        severity: warning
        disabled: false
      - name: string-format
        severity: warning
        disabled: false
        arguments:
          - - 'core.WriteError[1].Message'
            - '/^([^A-Z]|$)/'
            - must not start with a capital letter
          - - 'fmt.Errorf[0]'
            - '/(^|[^\.!?])$/'
            - must not end in punctuation
          - - panic
            - '/^[^\n]*$/'
            - must not contain line breaks
      - name: struct-tag
        arguments:
          - "json,inline"
          - "bson,outline,gnu"
        severity: warning
        disabled: false
      - name: superfluous-else
        severity: warning
        disabled: false
      - name: time-equal
        severity: warning
        disabled: false
      - name: time-naming
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - [ "ID" ] # AllowList
          - [ "VM" ] # DenyList
      - name: var-declaration
        severity: warning
        disabled: false
      - name: unconditional-recursion
        severity: warning
        disabled: false
      - name: unexported-naming
        severity: warning
        disabled: false
      - name: unexported-return
        severity: warning
        disabled: false
      - name: unhandled-error
        severity: warning
        disabled: false
        arguments:
          - "fmt.Printf"
          - "myFunction"
      - name: unnecessary-stmt
        severity: warning
        disabled: false
      - name: unreachable-code
        severity: warning
        disabled: false
      - name: unused-parameter
        severity: warning
        disabled: false
      - name: unused-receiver
        severity: warning
        disabled: false
      - name: useless-break
        severity: warning
        disabled: false
      - name: waitgroup-by-value
        severity: warning
        disabled: false
  decorder:
    dec-order:
      - type
      - const
      - var
      - func
    disable-dec-order-check: false
    disable-init-func-first-check: false
    disable-dec-num-check: false